### ISSUE TITLE
Python install error

### ISSUE THREAD

**Issue by edwardabraham** [stencila/stencila#1714] opened 2023-10-24 20:33 UTC
I tried to naively run the pip install and hit an error:
```
edward@whio:~/dragonfly$ python -m pip install stencila
Collecting stencila
  Downloading stencila-2.0.0a18.tar.gz (248 kB)
     |████████████████████████████████| 248 kB 6.6 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmpuqnfzzat prepare_metadata_for_build_wheel /tmp/tmpsh2mfswj
         cwd: /tmp/pip-install-x6xz8rwg/stencila
    Complete output (6 lines):
    💥 maturin failed
      Caused by: failed to normalize path `python\Cargo.toml`
      Caused by: No such file or directory (os error 2)
    Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-tksowm0n', '--interpreter', '/usr/bin/python3']' returned non-zero exit status 1.
    Checking for Rust toolchain....
    Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-tksowm0n --interpreter /usr/bin/python3`
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpuqnfzzat prepare_metadata_for_build_wheel /tmp/tmpsh2mfswj Check the logs for full command output.
```

**Comment by nokome** [comment] 2023-10-25 01:35
Thanks for this @edwardabraham. To help me debug this, could you tell me what OS (including version) and arch you are on?

**Comment by edwardabraham** [comment] 2023-10-25 02:01
I am on Ubuntu 20.04.6 LTS (Intel x86_64)

**Comment by edwardabraham** [comment] 2023-10-25 02:02
I am running pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

**Comment by nokome** [comment] 2023-10-25 02:23
Thanks. I think the problem is that we don't yet build a binary wheel for Python 3.8 but do create a Python suorce distribution (which is incomplete because it does not include all the Rust code including the `python/Cargo.toml`). So the solution here would seem to be to:

- [ ] create a `stencila-2.0.0a18-cp38-cp38-manylinux_2_34_x86_64.whl`
- [x] not create a source distributions

**Comment by nokome** [comment] 2023-10-25 20:44
I made a new release `v2.0.0-alpha.19` which has wheels build for more Python versions (added 3.8 & 3.12) and platforms (added MacOS ARM64): https://pypi.org/project/stencila/2.0.0a19/#files.

Installation across many Python versions and platforms is tested on each release as part of the `Install` workflow: https://github.com/stencila/stencila/actions/runs/6645899861. It is failing for older Python versions on MacOS ARM64 (because Github does not support all combinations) but I'm hoping it fixes install on your particular setup @edwardabraham.

**Comment by edwardabraham** [comment] 2023-10-26 00:28
Success! It seems that running `pip install --upgrade pip` on my part was also part of the solution.

**Comment by nokome** [comment] 2023-10-26 01:45
Great thanks! Yes, I was experimenting in a 3.8 Docker container and came to the same conclusion. There was change in the pip dependency resolver: https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020. I'll put a note about this in the docs.

Unfortunately, I've also discovered some other issues with version of Python < 3.11 (which I developed this against). So I'm going to have to fix those before it's usable.

I'll close this particular issue though.

**Closed by nokome** 2023-10-26 01:45 UTC
Labels: priority: first, type: bug, type: releases
