### ISSUE TITLE
Towards a future-proof Stencila file format

### ISSUE THREAD

**Issue by michael** [stencila/stencila#228] opened 2017-03-20 10:18 UTC
On the way to Kaikoura @nokome and I discussed how we would evolve the
source format. E.g. it would be necessary to implement migrations if we change
the HTML serialization. Unless we were able to decide now on the serialization
and don't change it.

How about moving towards Stencila JATS? (= data-driven JATS, with some simplifications)

Differences to JATS:

- Flat headings instead of sections
- HTML is used in the body whenever sufficient tags available (e.g. `<a>` instead of `<ext-link>`, `<strong>` instead of `<bold>`)
- Introduce custom tags for Stencila-specific content. E.g. `<cell>`, `<inline-cell>`, `<input>`

Advantages of using this as the primary source format from the beginning:

- Not an island format
- No `<div data-type="...">` hacks.
- No wasted energy on discussing our own serialization (just follow JATS)
- Standardized metadata encoding
- Ability to write an XML:Schema to validate Stencila source files
- Very easy to convert to and from JATS Standard
- Ability to propose Stencila tag extensions to the JATS community
- One day we can merge Stencila+Texture efforts without extra conversion/migration efforts

Here's an example Stencila JATS file:

http://cdn.substance.io/stencila-jats.xml

**Comment by nokome** [comment] 2017-03-20 17:40
I propose that we use `<output>` not `<inline-cell>`. This would be a change to naming and semantics.

It is easier to explain the `input` -> `cell` -> `output`. Inputs are source nodes in the dependency graph. Outputs are sink nodes. Cells do things with the data in between: they can assign to a variable and thus insert a new node into the graph (they can also act as sinks if no variable is assigned to). 

Currently, "inline cells" are able to assign to variables. This may be convenient in a few cases but it also feels like it mixes concepts and creates a hidden side effect. Visually, cells are very explicit in their side effects - you can reveal all cells and follow the data flow through the document. With inline cells that assign to a variable it is much more hidden.

**Comment by michael** [comment] 2017-03-20 20:26
`<output>` makes sense to me. And you are right, that there's no visual clue right now that shows you that an inline-cell is assigning to a variable.

**Comment by michael** [comment] 2017-03-21 11:34
Thought more about the option of using Pure JATS as the primary source format.

Let's assume:

Idea: Stencila expressed as pure JATS.

  - Every Stencila document is a valid JATS document
    - Only Stencila-specific attributes are added to existing JATS content elements
    - We'll stick with our internal concepts (cell, input, output etc.), just use
      JATS to encode them, so the static output is modelled in JATS, and Stencila
      specific hints are provided via attribute extensions. E.g. s:type="cell" turns
      a preformat element into an executable code chunk.
  - All generated content by Stencila must have a static JATS representation
    - Stencila Desktop may render an interactive Visualization, but
      we must always provide an image as a static version

Advantages:

  - No Island™ format from the beginning
  - Every Stencila document will be printable, archivable, indexable using existing tools and services
  - We will always be reminded to not forget about a suitable output of

Disadvantages:

  - More verbose than a custom format
  - Not really semantic (e.g. graphic element used for all kind of figure-ish content, such as plots)
  - The serialization is output-first not input-first, so we use a regular text annotation
    `<named-content s:type="select">` instead of `<select>`.

For discussion:

  - Do all Stencila-produced values fit in an XML attribute, as JSON?
  - We'd have to avoid extra XML elements, in order to not violate the JATS Standard
  - Not sure if there's an official way to mark a JATS element as hidden. It
    would be nice to control which preformat elements are actually shown in the
    static publication.

Here's an example modelling the node types we have so far.

Thoughts?

http://cdn.substance.io/stencila-pure-jats.xml

**Comment by michael** [comment] 2017-03-22 20:38
Just dumping thoughts... A nice thing about using pure JATS for serialization would be that we consider JATS no longer 'just' an output format, but keep the reproducible bits in it. This means an XML available on PubMed would be reproducible when created with Stencila. If we just "export" to JATS the beauty would be lost.

Let's discuss more..  for 0.25 we will stick with HTML anyways.

**Comment by nokome** [comment] 2017-04-01 07:56
As @michael has said there are advantages of having a non-custom internal format:
- not spending hours reinventing the wheel in defining a format
- not being an island - "why didn't they use an existing standard!"
- making use of existing converters from/to other formats and the internal format

But we also need to remember that Stencila users don't ever need to be aware of what the internal format is. It should be "invisible" to them. Regardless of what the internal format is, if they open a JATS file using Stencila, then when they save that file it is saved to JATS. If they open a Markdown file using Stencila, then it gets saved as Markdown. In the editor,  commands/capabilities will be enabled/disabled depending on the format - e.g if your editing a Markdown file then you can't  have track changes on.

Because of this "invisibility" of the internal format I don't think it really matters if we need to add hacks like `<div data-type="...">` or `<named-content s:type="select">`.

So I propose that the two most important criteria for choosing an existing format as our internal format are:
- widespread adoption
- easy to convert to/from in memory models (i.e. XML or HTML based)
- existing converters and/or easy to develop new converters for other formats

Given that, I would like to propose the [Open Document Format (ODF)](https://en.wikipedia.org/wiki/OpenDocument). It is an both an Organization for the Advancement of Structured Information Standards (OASIS)  and ISO standard and has been mandated by both governments and international organisations.

It defines XML schemas for text documents, spreadsheets, presentations, graphics and formulae. It is thus able to provide the advantages of  a non-custom format for all of the types of documents that we are likely to have in Stencila.

We could perhaps use the approach being used in Texture of generating the document Nodes based on the schema. Or we could just start with the basics and add complexity later.

If we were just dealing with text documents then I'd say there would be good reason to choose JATS. But if we really are trying to be the "office suite for reproducible research" then it seems to me we'd really have to have some very good reasons not to use ODF as an internal format. Once again, users wouldn't need to actually see that's what they are using in the internal buffer, they could use whatever on-disk format they want.

**Comment by michael** [comment] 2017-04-01 16:17
ODF could make sense definitely. Need to look at it closer. Did you find some minimal sample documents we could look at?

**Comment by nokome** [comment] 2017-04-01 18:10
This is a useful little guide with some minimal examples: https://mashupguide.net/1.0/html/ch17s03.xhtml

**Closed** 2017-12-21 04:33 UTC
