### ISSUE TITLE
Inserting new cell always shows an error

### ISSUE THREAD

**Issue by Integral** [stencila/stencila#520] opened 2018-02-06 22:41 UTC
Every time when I'm inserting cell I see this error: 
<img width="799" alt="screen shot 2018-02-07 at 01 38 47" src="https://user-images.githubusercontent.com/182010/35888113-ab98c626-0ba7-11e8-8cae-8d3045ff7cf8.png">

I understand that the engine tries to execute cell immediately, but it's really annoying and there is no reason to execute cell without content... 

Typing and removing symbols in cell also produce errors (because of reexecution on cell editing), it's annoying also, maybe we should debounce execution or just don't show error immediately? 
Also, don't know how it's working exactly, but what will happen if cell triggers serious computation? What will happen on editing? Can it be potential reason for freezing or slow typing?

**Comment by oliver----** [comment] 2018-02-07 13:08
This is duplicate of #509.

**Closed by oliver----** 2018-02-07 13:08 UTC
