### ISSUE TITLE
Choice of open source licence

### ISSUE THREAD

**Issue by sirinath** [stencila/stencila#176] opened 2016-04-24 15:47 UTC
1st and foremost this is a great project. Is it possible to move to ASL 2.0 as this is more business friendly and is whitelisted in many organisations?

**Comment by nokome** [comment] 2016-04-24 20:03
Hi @sirinath, thanks for the comment and suggestion to change to ASL, MIT or BSD.

Changing the license is an option - and would presumably be easier to do now, when there are only three authors (@michael and @oliver---- pinging you), than later when there might be more.

I'd like to open the discussion up here regarding the choice of open source license to see what others think (so I've edited your title to be more generic) before making any change.

**Comment by esetera** [comment] 2016-04-24 22:27
The more permissive the better IMHO but it does relate to business models. I would recommend pinging James Vasile about this, he is on the advisory board for Coko and is an IP lawyer who specialises in open source.

**Comment by sirinath** [comment] 2016-04-25 03:32
Also see discussion at: https://github.com/PerfectlySoft/Perfect/issues/131

**Comment by nokome** [comment] 2016-11-03 23:12
I have been reconsidering licensing given the complete reorganisation of Stencila into decoupled packages and more of a focus on protocols for reproducible computing.

The Free Software Foundation recommends that for libraries which ["implement free standards that are competing against restricted standards"](https://www.gnu.org/licenses/license-recommendations.html)

> widespread use of the code is vital for advancing the cause of free software, and does more good than a copyleft on the project's code would do ... In these special situations, we recommend the Apache License 2.0.

In Stencila's case, we are not exactly competing against restricted standards. But the principal is the same: a more permissive library would promote greater uptake of the open and reproducible research that Stencila enables. The proposal to [switch cpp-ethereum to Apache 2.0](https://bobsummerwill.com/2016/07/12/ethereum-everywhere/) has a similar rationale.

I propose to switch all the main repos, `node`, `py`, `r`, `cpp` etc to Apache 2.0 (as well as this one, even though, currently it contains no active code). When there are many code contributors there can be [substantial work in switching licences](https://bobsummerwill.com/2016/07/12/c-re-licensing-plan/). So it makes sense to do this now while there is only one :smile:

**Comment by nokome** [comment] 2016-12-21 00:54
The following repos have been moved to Apache-2.0: node, py, r, cpp, web. Closing

**Closed by nokome** 2016-12-21 00:54 UTC

**Comment by rudolfolah** [comment] 2018-07-14 13:30
Curious to know if using the GPLv3 would have affected the code/documents that people write within the tool. It's good to see the Apache license being used though.

**Comment by nokome** [comment] 2018-07-17 22:07
Hey @rudolfolah : that's an interesting question! One I'm not qualified to answer. But I suspect GPLv3 would not have affected code in documents because you are not "linking" to the Stencila code, just using it as an execution engine for your code.
